spring.application.name=aws-s3-assurance
server.port=${PORT:8080}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
app.aws.region=${AWS_REGION:us-east-2}
app.aws.s3.bucket=${AWS_S3_BUCKET:amzn-s3-assurance-826917684746-us-east-2-an}
